---
deployment:
  tasks:
    - echo "Starting deployment tasks."
    - export DEPLOYMENT_DIR=$PWD
    - echo "Deployment directory: $DEPLOYMENT_DIR"
    - source /home/$USER/virtualenv/repositories/simplePhysiotherapyCentreHMS/3.8/bin/activate
    - pip install -r requirements.txt
    - touch tmp/restart.txt
    - echo "Deployment completed successfully."
