---
deployment:
  tasks:
    - echo "Starting deployment tasks."
    - export DEPLOYMENT_DIR=$PWD
    - echo "Deployment directory: $DEPLOYMENT_DIR"
    - /home/$USER/virtualenv/seaside-hms/3.8/bin/pip install -r requirements.txt
    - touch tmp/restart.txt
